spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dll
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml